stream_srv: sctp: Log error cause of COMM_LOST event
RFC 6458 6.1.1:
"""
sac_error:  If the state was reached due to an error condition (e.g.,
SCTP_COMM_LOST), any relevant error information is available in
this field.  This corresponds to the protocol error codes defined
in [RFC4960].
"""
Change-Id: Ie48360d22ce1e35eefb1a305dde106948dfa80e8