Use %zu for size_t
Fix that this doesn't build for debian 13 armv7l with errors like:

  osmo-amr-inspect.c:138:53: error: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'size_t' {aka 'unsigned int'} [-Werror=format=]
    138 |                 printf("  Payload has no padding (%lu bits with offset 10)\n", ft_bits);
        |                                                   ~~^                          ~~~~~~~
        |                                                     |                          |
        |                                                     long unsigned int          size_t {aka unsigned int}

Related: OS#6828
Change-Id: I81f6d26623544c259199099beb54d14f5788a9e4
(cherry picked from commit c49977d48bc9f18d4124caae3e65f860ebc28136)